### ISSUE TITLE
Registro a la OFMI

### ISSUE THREAD

**Issue by Felipe-Focil** [omegaup/website-OFMI#22]
Para tomar como referencia el actual registro [LINK](https://docs.google.com/forms/d/1iYu0ggHGh2Bd5ZlRdXUPPzS4kbBfozmz4ezdKrF7a-Y/edit)

Para que la participante pueda registrarse para participar en la OFMI en curso debe introducir los siguientes datos que se pedirán en un formulario (todos los campos son requeridos a excepción de los marcados como opcional):

- [x] Nombres
- [x] Apellidos
- [ ] CURP
- [x] Nombre Completo de Diploma
- [x] Pronombres
- [x] Fecha de Nacimiento
- [x] Pais de Residencia
  - [x] Si es Mexico [Dropdown]
     - [x] Estado
     - [x] Ciudad
   - [x] Si no es Mexico [Input]
     - [x] Pais
     - [x] Estado
     - [x] Ciudad
- [x] Escuela
   - [x] Dropdown de escuelas
   - [x] Agregar nueva escuela
- [x] Escolaridad
  - [x]  Primaria
  - [x]  Secundaria
  - [x]  Preparatoria
- [x] Año / Semestre [Dropdown]
  - [x] Primaria o Preparatoria (1-6)
  - [x] Secundaria (1-3)
- [ ] Textbox para mandar mensaje del equipo organizador
- [x] Checkbox si quieren recibir la playera de la competencia y la medalla en caso de que ganen medalla (SOLO MEXICO)
   - [x]  Nombre de persona que puede recibir el paquete en el domicilio
   - [x] Teléfono de la persona que puede recibir el paquete en el domicilio (10 digitos)
   - [x] Calle
   - [x] Número exterior
   - [x] Numero Interior (Opcional)
   - [x] Colonia
   - [ ] Código postal
   - [x] Municipio
   - [x] Estado (Dropdown)
   - [x] Talla de playera 
      - [x] S (chica)
      - [x] M (mediana)
      - [x] L (grande)
      - [x] XL (extra grande)
   - [x] Tipo de corte de playera (mostrar imágenes como en el google form)
      - [x] Tipo A (recta)
      - [x] Tipo B (acinturada)

**Comment by Felipe-Focil** [comment]
Nice To Have

- [ ] Validar que la dirección existe. 
   - [ ] Podemos empezar con validar que el código postal coincide con colonia y estado
- [ ] Si alguna validación no se cumple (falla) no se puede completar el registro y se muestra la razón.
- [ ]  Si ya se habían registrado para alguna OFMI pasada, prellenar los datos.

**Comment by aaron-diaz** [comment]
Estoy trabajando en esto. Pronto subire mis cambios.

**Comment by Juanito98** [comment]
Ya está
