### ISSUE TITLE
Regresar mejor error para registro duplicado

### ISSUE THREAD

**Issue by andreasantillana** [omegaup/website-OFMI#33]
está regresando el error de prisma sin ser parseado

![image](https://github.com/omegaup/website-OFMI/assets/5167417/0a8b460b-5453-41b2-8335-7686f06e779e)

**Comment by Juanito98** [comment]
<img width="631" alt="image" src="https://github.com/user-attachments/assets/f1161324-9df1-4ed7-8abd-5d053f04e51e">
